### ISSUE TITLE
Unable to launchbecause of Expired credentials found error.

### ISSUE THREAD

**Issue by Timboh56** [blake-education/aws-cfn-bootstrap#1]
Hi, I was wondering if you a clue on what this error means:

2015-05-14 22:16:35,631 [INFO] Scheduling next credential refresh in 59.555842825 seconds
2015-05-14 22:16:45,657 [ERROR] Expired credentials found; skipping process
2015-05-14 22:17:05,658 [ERROR] Expired credentials found; skipping process
2015-05-14 22:17:25,659 [INFO] command processing is alive.
2015-05-14 22:17:25,659 [ERROR] Expired credentials found; skipping process
2015-05-14 22:17:35,187 [INFO] Refreshing listener credentials
2015-05-14 22:17:35,188 [DEBUG] Get listener credentials for listener i-2b499be9 in stack arn:aws:cloudformation:us-west-1:325191781770:stack/awseb-e-pipbetduch-stack/0bab48b0-f416-11e4-955e-50d5017decd2
2015-05-14 22:17:45,660 [ERROR] Expired credentials found; skipping process
2015-05-14 22:18:05,661 [ERROR] Expired credentials found; skipping process
2015-05-14 22:18:25,662 [ERROR] Expired credentials found; skipping process
2015-05-14 22:18:35,188 [WARNING] Timeout of 60 seconds breached
2015-05-14 22:18:35,189 [ERROR] Client-side timeout
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cfnbootstrap/util.py", line 158, in _retry
    return f(_args, *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/cfnbootstrap/util.py", line 227, in _timeout
    raise TimeoutError("Execution did not succeed after %s seconds" % duration)
TimeoutError

I am unable tod eploy at the moment because that error is printed in my log repeatedly, it times out. I have checked my credentials secret key and access key and both are correct. what else could be a source of this?

**Comment by raimo** [comment]
+1
