### ISSUE TITLE
cfn-init tool sometimes fails on in locales with utf-8 default codepage

### ISSUE THREAD

**Issue by pbobov** [blake-education/aws-cfn-bootstrap#2]
cfn-init tool sometimes fails to execute commands on machines with utf-8 default code page (for example on machines with Chinese locale).

`2015-07-16 21:52:04,809 [ERROR] Unhandled exception during build: 'utf8' codec can't decode byte 0xd2 in position 0: invalid continuation byte
Traceback (most recent call last):
  File "cfn-init", line 123, in <module>
  File "cfnbootstrap\construction.pyc", line 117, in build
  File "cfnbootstrap\construction.pyc", line 502, in build
  File "cfnbootstrap\construction.pyc", line 513, in run_config
  File "cfnbootstrap\construction.pyc", line 125, in run_commands
  File "cfnbootstrap\command_tool.pyc", line 116, in apply
  File "encodings\utf_8.pyc", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd2 in position 0: invalid continuation byte`

cfn-init tries to print stdout bytes as string. But the default code page is utf-8 and not all combinations of bytes make valid utf-8 strings.

[command_tool.py](https://github.com/blake-education/aws-cfn-bootstrap/blob/master/cfnbootstrap/command_tool.py)
…
log.info("Command %s succeeded", name)
log.debug("Command %s output: %s", name, commandResult.stdout) 
…

**Comment by svdgraaf** [comment]
+1 :(

**Comment by tvb** [comment]
+1 

```
$ sudo /usr/local/bin/cfn-init -s "acceptance" -r "RestApplicationAutoScalingGroup" --region "eu-central-1"
/usr/local/lib/python2.7/dist-packages/cfnbootstrap/packages/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 874, in emit
    stream.write(fs % msg.encode("UTF-8"))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 55: ordinal not in range(128)
Logged from file util.py, line 473
```
